In [9]:
from __future__ import print_function
import numpy as np

d = 64                           # dimension
nb = 1000000            # database size
nq = 10000                 # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

True
1000000
[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751738 7.20763   7.2511625]
 [0.        6.3235645 6.684581  6.799946 ]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.527987  7.6628466]
 [0.        6.7638035 7.2951202 7.3688145]]
[[ 774  175  917  413]
 [  98   66  357  596]
 [ 504  263  740  738]
 [ 756 1102  454  353]
 [ 352  381  545  264]]
[[10179 10714  9864  8813]
 [ 9762 10013  9720 10405]
 [ 9229  9510 10039 10602]
 [10584  9725  9787  9816]
 [ 9464  9635 10199  9180]]


In [10]:
faiss.write_index(index, "./saved-index.faiss")

In [11]:
loaded = faiss.read_index("./saved-index.faiss")

In [12]:
D, I = loaded.search(xb[:5], k) # sanity check
print(I)
print(D)

[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751738 7.20763   7.2511625]
 [0.        6.3235645 6.684581  6.799946 ]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.527987  7.6628466]
 [0.        6.7638035 7.2951202 7.3688145]]


In [13]:
D, I = loaded.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[ 774  175  917  413]
 [  98   66  357  596]
 [ 504  263  740  738]
 [ 756 1102  454  353]
 [ 352  381  545  264]]
[[10179 10714  9864  8813]
 [ 9762 10013  9720 10405]
 [ 9229  9510 10039 10602]
 [10584  9725  9787  9816]
 [ 9464  9635 10199  9180]]
